<a href="https://colab.research.google.com/github/Rabiatou08/DI-Bootcamp/blob/main/%20week3/Day1/ExerciseXP/exo-xp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercice 1 : Création et manipulation de tableaux

In [ ]:
import numpy as np
arr= np.array([0, 1,3,4,5,6,7,8,9])
print(arr)

[0 1 3 4 5 6 7 8 9]


 Exercice 2 : Conversion de type et opérations sur les tableaux

In [ ]:
import numpy as np

arr = np.array([3.14, 2.17, 0, 1, 2])

arr_int = arr.astype(int)

print(arr_int)

[3 2 0 1 2]


Exercice 3 : Travailler avec des tableaux multidimensionnels

In [ ]:
import numpy as np
arr3 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires

In [ ]:
import numpy as np

arr2 = np.random.rand(4, 5)

print(np.round(arr2, 2))

[[0.36 0.64 0.13 0.97 0.4 ]
 [0.53 0.49 0.7  0.77 0.26]
 [0.55 0.13 0.71 0.92 0.99]
 [0.91 0.45 0.58 0.31 0.63]]


Exercice 5 : Indexation des tableaux

In [ ]:
import numpy as np
array = np.array(
    [[21,22,23,22,22],
 [20, 21, 22, 23, 24],
  [21,22,23,22,22]
     ])
print(array[1])

[20 21 22 23 24]


 Exercice 6 : Inversion des éléments

In [ ]:
import numpy as np
array= np.arange(0,10)
print(array[::-1])


[9 8 7 6 5 4 3 2 1 0]


Exercice 7 : Matrice identité

In [ ]:
import numpy as np
array = np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8 : Fonctions agrégées simples

In [ ]:
import numpy as np
array = np.arange(0,10)
somme = np.sum(array)
Moyenne= np.average(array)
print("Sum :", somme)
print("Average :", Moyenne)


Sum : 45
Average : 4.5


Exercice 9 : Créer un tableau et modifier sa structureExercice 9 : Créer un tableau et modifier sa structure

In [ ]:
import numpy as np
array = np.arange(1, 21).reshape(4,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


 Exercice 10 : Sélection conditionnelle des valeurs

In [ ]:
import numpy as np
array= np.arange(1,10)
impair = array[array % 2 != 0]
print(impair)

[1 3 5 7 9]
